swagger: "2.0"
info:
  title: Tolymer API
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
tags:
  - name: user_token
  - name: users
  - name: current_user
  - name: groups
  - name: group_members
  - name: group_events
  - name: events
  - name: event_members
  - name: event_games
