version: '3.3'
services:
  db:
    image: postgres:10.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
       - db-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - .:/app
      - bundle:/app/vendor/bundle
    environment:
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      DATABASE_HOST: db
    tty: true
    stdin_open: true
    command: ["script/start.sh"]

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - '8080:8080'
    environment:
      API_URL: http://localhost:3000/swagger

volumes:
  db-data:
  bundle:
