version: '3.3'
services:
  db:
    image: postgres:10.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '15432:5432'
    volumes:
       - db-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '5000:5000'
    depends_on:
      - db
    volumes:
      - .:/app
      # - bundle:/app/vendor/bundle
    environment:
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      DATABASE_HOST: db
    tty: true
    stdin_open: true
    command: ["bin/rails", "runner", "grpc_server.rb"]

  envoy:
    build:
      context: .
      dockerfile: Dockerfile.envoy
    ports:
      - '8080:8080'

volumes:
  db-data:
  bundle:
