# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tolymer.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "tolymer.CreateEventRequest" do
    optional :title, :string, 1
    optional :description, :string, 2
    optional :date, :string, 3
    repeated :members, :string, 4
  end
  add_message "tolymer.CreateEventResponse" do
    optional :event_token, :string, 1
  end
  add_message "tolymer.GetEventRequest" do
    optional :event_token, :string, 1
  end
  add_message "tolymer.GetEventResponse" do
    optional :event, :message, 1, "tolymer.Event"
  end
  add_message "tolymer.UpdateEventRequest" do
    optional :event_token, :string, 1
    optional :title, :string, 2
    optional :description, :string, 3
    optional :date, :string, 4
    repeated :members, :string, 5
  end
  add_message "tolymer.UpdateEventResponse" do
    optional :result, :bool, 1
  end
  add_message "tolymer.CreateGameRequest" do
    optional :event_token, :string, 1
    repeated :scores, :message, 2, "tolymer.Score"
  end
  add_message "tolymer.CreateGameResponse" do
    optional :game_id, :int32, 1
  end
  add_message "tolymer.UpdateGameRequest" do
    optional :game_id, :int32, 1
    repeated :scores, :message, 2, "tolymer.Score"
  end
  add_message "tolymer.UpdateGameResponse" do
    optional :result, :bool, 1
  end
  add_message "tolymer.Event" do
    optional :token, :string, 1
    optional :title, :string, 2
    optional :description, :string, 3
    optional :date, :string, 4
    repeated :members, :message, 5, "tolymer.Member"
    repeated :games, :message, 6, "tolymer.Game"
  end
  add_message "tolymer.Member" do
    optional :id, :int32, 1
    optional :name, :string, 2
  end
  add_message "tolymer.Game" do
    optional :id, :int32, 1
    optional :event_id, :int32, 2
    repeated :scores, :message, 3, "tolymer.Score"
  end
  add_message "tolymer.Score" do
    optional :member_id, :int32, 1
    optional :point, :int32, 2
  end
end

module Tolymer
  CreateEventRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("tolymer.CreateEventRequest").msgclass
  CreateEventResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("tolymer.CreateEventResponse").msgclass
  GetEventRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("tolymer.GetEventRequest").msgclass
  GetEventResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("tolymer.GetEventResponse").msgclass
  UpdateEventRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("tolymer.UpdateEventRequest").msgclass
  UpdateEventResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("tolymer.UpdateEventResponse").msgclass
  CreateGameRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("tolymer.CreateGameRequest").msgclass
  CreateGameResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("tolymer.CreateGameResponse").msgclass
  UpdateGameRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("tolymer.UpdateGameRequest").msgclass
  UpdateGameResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("tolymer.UpdateGameResponse").msgclass
  Event = Google::Protobuf::DescriptorPool.generated_pool.lookup("tolymer.Event").msgclass
  Member = Google::Protobuf::DescriptorPool.generated_pool.lookup("tolymer.Member").msgclass
  Game = Google::Protobuf::DescriptorPool.generated_pool.lookup("tolymer.Game").msgclass
  Score = Google::Protobuf::DescriptorPool.generated_pool.lookup("tolymer.Score").msgclass
end
