# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: tolymer.proto for package 'tolymer'

require 'grpc'
require 'tolymer_pb'

module Tolymer
  module Guest
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'tolymer.Guest'

      rpc :CreateEvent, CreateEventRequest, CreateEventResponse
      rpc :GetEvent, GetEventRequest, GetEventResponse
      rpc :UpdateEvent, UpdateEventRequest, UpdateEventResponse
      rpc :CreateGame, CreateGameRequest, CreateGameResponse
      rpc :UpdateGame, UpdateGameRequest, UpdateGameResponse
    end

    Stub = Service.rpc_stub_class
  end
end
