default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: password
  host: db
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tolymer_development

test:
  <<: *default
  database: tolymer_test

production:
  url: <%= ENV['DATABASE_URL'] %>
